"use client";

import Link from "next/link";
import { useQuery } from "@tanstack/react-query";
import { Card, CardHeader, CardTitle, CardContent, CardDescription, CardFooter } from "@/components/ui/card";
import { List, ChevronRight, FileText, AlertCircle } from "lucide-react";
import { FormattedDate } from "@/components/common";
import type { ReportManifestItem } from "@/types"; // Added type import

const fetchReportManifest = async (): Promise<ReportManifestItem[]> => {
  const response = await fetch("/all_analysis_runs_manifest.json");
  if (!response.ok) {
    throw new Error('Network response was not ok');
  }
  return response.json();
};

export default function ReportListPage() {
  const { data: reportManifest, isLoading, error, isError } = useQuery<ReportManifestItem[], Error>({
    queryKey: ["reportManifest"],
    queryFn: fetchReportManifest,
  });

  if (isLoading) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-slate-100 to-slate-100">
        <div className="text-center">
          <div className="w-16 h-16 border-4 border-blue-500 border-dashed rounded-full animate-spin mx-auto mb-4"></div>
          <p className="text-xl text-slate-700">Loading Available Reports...</p>
        </div>
      </div>
    );
  }

  if (isError || !reportManifest) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-red-50 to-red-100/30">
        <div className="text-center p-8 bg-white shadow-xl rounded-2xl max-w-lg">
          <div className="w-20 h-20 bg-gradient-to-br from-red-100 to-red-200 rounded-3xl flex items-center justify-center mx-auto mb-6 shadow-lg">
            <AlertCircle className="w-10 h-10 text-red-500" />
          </div>
          <h1 className="text-3xl font-bold text-slate-900 mb-4">Error Loading Report List</h1>
          <p className="text-slate-600 mb-6 text-lg">Could not load the list of available reports.</p>
          {error && <pre className="text-xs text-red-700 bg-red-50 p-4 rounded-md text-left mt-4">{error.message}</pre>}
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 via-white to-blue-50/30 py-12">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        <header className="text-center mb-16">
          <div className="inline-flex items-center gap-3 bg-gradient-to-r from-blue-50 to-indigo-50 text-blue-700 px-6 py-3 rounded-2xl text-sm font-semibold mb-8 border border-blue-100 shadow-sm">
            <FileText className="w-5 h-5" />
            Website Analysis Archive
          </div>
          <h1 className="text-5xl font-bold text-slate-900 mb-6 tracking-tight leading-tight">Analysis Reports</h1>
          <p className="text-xl text-slate-600 max-w-2xl mx-auto leading-relaxed">
            Browse through the comprehensive UX/UI evaluations generated by the analysis pipeline.
          </p>
        </header>

        {reportManifest.length === 0 ? (
          <Card className="text-center p-10 border-slate-200/80 bg-white shadow">
            <CardHeader className="p-0 mb-6">
              <div className="w-20 h-20 bg-gradient-to-br from-slate-50 to-slate-100 rounded-3xl flex items-center justify-center mx-auto mb-6 shadow-lg">
                <List className="h-10 w-10 text-slate-400" />
              </div>
              <CardTitle className="text-2xl font-semibold text-slate-800">No Reports Found</CardTitle>
            </CardHeader>
            <CardContent className="p-0">
              <p className="text-slate-600 text-lg">There are no analysis reports currently available in the manifest.</p>
            </CardContent>
          </Card>
        ) : (
          <div className="space-y-8">
            {reportManifest.map((report) => (
              <Link key={report.id} href={`/report/${report.id}`} className="block group outline-none focus-visible:ring-2 focus-visible:ring-blue-500 focus-visible:ring-offset-4 focus-visible:ring-offset-slate-50 rounded-2xl">
                <Card className="transition-all duration-300 ease-in-out group-hover:shadow-2xl group-hover:border-blue-400/70 border-slate-200/80 bg-white rounded-2xl overflow-hidden group-hover:scale-[1.015]">
                  <CardHeader className="p-6 sm:p-8">
                    <CardTitle className="text-2xl font-semibold text-slate-900 group-hover:text-blue-700 transition-colors">{report.name}</CardTitle>
                    <CardDescription className="text-sm text-slate-500 pt-2">
                      Generated on: <FormattedDate dateString={report.date} />
                    </CardDescription>
                  </CardHeader>
                  <CardContent className="p-6 sm:p-8 pt-0">
                    <p className="text-slate-600 leading-relaxed line-clamp-2">{report.description || "Detailed UX/UI analysis and strategic recommendations for this website."}</p>
                  </CardContent>
                  <CardFooter className="p-6 sm:p-8 bg-slate-50/70 border-t border-slate-100/90">
                    <div className="text-sm font-semibold text-blue-600 group-hover:text-blue-700 flex items-center gap-1.5 transition-colors duration-300">
                      View Full Report
                      <ChevronRight className="h-4 w-4 transform transition-transform duration-300 group-hover:translate-x-1" />
                    </div>
                  </CardFooter>
                </Card>
              </Link>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}